# Podfile
use_frameworks!

target 'spaceship-template' do
    pod 'RxSwift', '6.1.0'
    pod 'RxCocoa', '6.1.0'
end

# RxTest and RxBlocking make the most sense in the context of unit/integration tests
target 'spaceship-templateTests' do
    pod 'RxBlocking', '6.1.0'
    pod 'RxTest', '6.1.0'
end